<?php

namespace ContainerOXsEr9L;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTaxeVenteControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\TaxeVenteController' shared autowired service.
     *
     * @return \App\Controller\TaxeVenteController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/TaxeVenteController.php';

        $container->services['App\\Controller\\TaxeVenteController'] = $instance = new \App\Controller\TaxeVenteController(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));

        $instance->setContainer(($container->privates['.service_locator.mx0UMmY'] ?? $container->load('get_ServiceLocator_Mx0UMmYService'))->withContext('App\\Controller\\TaxeVenteController', $container));

        return $instance;
    }
}
