<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Establishments extends \App\Entity\Establishments implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Establishments' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Establishments' . "\0" . 'type', '' . "\0" . 'App\\Entity\\Establishments' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Establishments' . "\0" . 'email', '' . "\0" . 'App\\Entity\\Establishments' . "\0" . 'Speciality', '' . "\0" . 'App\\Entity\\Establishments' . "\0" . 'portable', '' . "\0" . 'App\\Entity\\Establishments' . "\0" . 'telephone', '' . "\0" . 'App\\Entity\\Establishments' . "\0" . 'Site_internet', '' . "\0" . 'App\\Entity\\Establishments' . "\0" . 'fax', '' . "\0" . 'App\\Entity\\Establishments' . "\0" . 'RC', '' . "\0" . 'App\\Entity\\Establishments' . "\0" . 'INPE', '' . "\0" . 'App\\Entity\\Establishments' . "\0" . 'Adresse', '' . "\0" . 'App\\Entity\\Establishments' . "\0" . 'ville', '' . "\0" . 'App\\Entity\\Establishments' . "\0" . 'secteur', '' . "\0" . 'App\\Entity\\Establishments' . "\0" . 'Region', '' . "\0" . 'App\\Entity\\Establishments' . "\0" . 'Code_postale', '' . "\0" . 'App\\Entity\\Establishments' . "\0" . 'pays', '' . "\0" . 'App\\Entity\\Establishments' . "\0" . 'statut', '' . "\0" . 'App\\Entity\\Establishments' . "\0" . 'ReasonForRejection', '' . "\0" . 'App\\Entity\\Establishments' . "\0" . 'DateModified', '' . "\0" . 'App\\Entity\\Establishments' . "\0" . 'DateCreated', '' . "\0" . 'App\\Entity\\Establishments' . "\0" . 'comptes'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Establishments' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Establishments' . "\0" . 'type', '' . "\0" . 'App\\Entity\\Establishments' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Establishments' . "\0" . 'email', '' . "\0" . 'App\\Entity\\Establishments' . "\0" . 'Speciality', '' . "\0" . 'App\\Entity\\Establishments' . "\0" . 'portable', '' . "\0" . 'App\\Entity\\Establishments' . "\0" . 'telephone', '' . "\0" . 'App\\Entity\\Establishments' . "\0" . 'Site_internet', '' . "\0" . 'App\\Entity\\Establishments' . "\0" . 'fax', '' . "\0" . 'App\\Entity\\Establishments' . "\0" . 'RC', '' . "\0" . 'App\\Entity\\Establishments' . "\0" . 'INPE', '' . "\0" . 'App\\Entity\\Establishments' . "\0" . 'Adresse', '' . "\0" . 'App\\Entity\\Establishments' . "\0" . 'ville', '' . "\0" . 'App\\Entity\\Establishments' . "\0" . 'secteur', '' . "\0" . 'App\\Entity\\Establishments' . "\0" . 'Region', '' . "\0" . 'App\\Entity\\Establishments' . "\0" . 'Code_postale', '' . "\0" . 'App\\Entity\\Establishments' . "\0" . 'pays', '' . "\0" . 'App\\Entity\\Establishments' . "\0" . 'statut', '' . "\0" . 'App\\Entity\\Establishments' . "\0" . 'ReasonForRejection', '' . "\0" . 'App\\Entity\\Establishments' . "\0" . 'DateModified', '' . "\0" . 'App\\Entity\\Establishments' . "\0" . 'DateCreated', '' . "\0" . 'App\\Entity\\Establishments' . "\0" . 'comptes'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Establishments $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getType(): ?\App\Entity\TypeEstablishments
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', []);

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setType(?\App\Entity\TypeEstablishments $type): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', [$type]);

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName(string $name): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail(string $email): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getSpeciality(): ?\App\Entity\SpecialityEstablishments
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSpeciality', []);

        return parent::getSpeciality();
    }

    /**
     * {@inheritDoc}
     */
    public function setSpeciality(?\App\Entity\SpecialityEstablishments $Speciality): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSpeciality', [$Speciality]);

        return parent::setSpeciality($Speciality);
    }

    /**
     * {@inheritDoc}
     */
    public function getPortable(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPortable', []);

        return parent::getPortable();
    }

    /**
     * {@inheritDoc}
     */
    public function setPortable(string $portable): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPortable', [$portable]);

        return parent::setPortable($portable);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelephone(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelephone', []);

        return parent::getTelephone();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelephone(string $telephone): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelephone', [$telephone]);

        return parent::setTelephone($telephone);
    }

    /**
     * {@inheritDoc}
     */
    public function getSiteInternet(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSiteInternet', []);

        return parent::getSiteInternet();
    }

    /**
     * {@inheritDoc}
     */
    public function setSiteInternet(string $Site_internet): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSiteInternet', [$Site_internet]);

        return parent::setSiteInternet($Site_internet);
    }

    /**
     * {@inheritDoc}
     */
    public function getFax(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFax', []);

        return parent::getFax();
    }

    /**
     * {@inheritDoc}
     */
    public function setFax(string $fax): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFax', [$fax]);

        return parent::setFax($fax);
    }

    /**
     * {@inheritDoc}
     */
    public function getRC(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRC', []);

        return parent::getRC();
    }

    /**
     * {@inheritDoc}
     */
    public function setRC(string $RC): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRC', [$RC]);

        return parent::setRC($RC);
    }

    /**
     * {@inheritDoc}
     */
    public function getINPE(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getINPE', []);

        return parent::getINPE();
    }

    /**
     * {@inheritDoc}
     */
    public function setINPE(string $INPE): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setINPE', [$INPE]);

        return parent::setINPE($INPE);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', []);

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse(string $Adresse): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', [$Adresse]);

        return parent::setAdresse($Adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getVille(): ?\App\Entity\Ville
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVille', []);

        return parent::getVille();
    }

    /**
     * {@inheritDoc}
     */
    public function setVille(?\App\Entity\Ville $ville): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVille', [$ville]);

        return parent::setVille($ville);
    }

    /**
     * {@inheritDoc}
     */
    public function getSecteur(): ?\App\Entity\Secteur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSecteur', []);

        return parent::getSecteur();
    }

    /**
     * {@inheritDoc}
     */
    public function setSecteur(?\App\Entity\Secteur $secteur): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSecteur', [$secteur]);

        return parent::setSecteur($secteur);
    }

    /**
     * {@inheritDoc}
     */
    public function getRegion(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegion', []);

        return parent::getRegion();
    }

    /**
     * {@inheritDoc}
     */
    public function setRegion(string $Region): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRegion', [$Region]);

        return parent::setRegion($Region);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodePostale(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodePostale', []);

        return parent::getCodePostale();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodePostale(string $Code_postale): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodePostale', [$Code_postale]);

        return parent::setCodePostale($Code_postale);
    }

    /**
     * {@inheritDoc}
     */
    public function getPays(): ?\App\Entity\Pays
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPays', []);

        return parent::getPays();
    }

    /**
     * {@inheritDoc}
     */
    public function setPays(?\App\Entity\Pays $pays): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPays', [$pays]);

        return parent::setPays($pays);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatut(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatut', []);

        return parent::getStatut();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatut(string $statut): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatut', [$statut]);

        return parent::setStatut($statut);
    }

    /**
     * {@inheritDoc}
     */
    public function getReasonForRejection(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReasonForRejection', []);

        return parent::getReasonForRejection();
    }

    /**
     * {@inheritDoc}
     */
    public function setReasonForRejection(string $ReasonForRejection): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReasonForRejection', [$ReasonForRejection]);

        return parent::setReasonForRejection($ReasonForRejection);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateModified(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateModified', []);

        return parent::getDateModified();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateModified(\DateTimeInterface $DateModified): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateModified', [$DateModified]);

        return parent::setDateModified($DateModified);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateCreated(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateCreated', []);

        return parent::getDateCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateCreated(\DateTimeInterface $DateCreated): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateCreated', [$DateCreated]);

        return parent::setDateCreated($DateCreated);
    }

    /**
     * {@inheritDoc}
     */
    public function getComptes(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComptes', []);

        return parent::getComptes();
    }

    /**
     * {@inheritDoc}
     */
    public function addCompte(\App\Entity\Compte $compte): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCompte', [$compte]);

        return parent::addCompte($compte);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCompte(\App\Entity\Compte $compte): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCompte', [$compte]);

        return parent::removeCompte($compte);
    }

}
